# -------------------------
# Shell
# -------------------------
shell pwsh -NoLogo

# -------------------------
# Window
# -------------------------
window_decorations none
confirm_os_window_close 0
window_padding_width 10
background_opacity 0.65
dynamic_background_opacity yes
enable_blur yes
title Terminal
class_name kitty
instance_name Terminal

# -------------------------
# Behaviour
# -------------------------
clipboard_control write-clipboard write-primary no-append
copy_on_select no

# -------------------------
# Font
# -------------------------
font_family FiraCode Nerd Font
bold_font FiraCode Nerd Font Bold
italic_font FiraCode Nerd Font Italic
font_size 11.0

# -------------------------
# Cursor
# -------------------------
cursor_shape block
cursor_blink_interval 0.75
cursor_stop_blinking_after 0

# -------------------------
# Scrolling
# -------------------------
wheel_scroll_multiplier 3.0

# -------------------------
# Colors
# -------------------------

include current-theme.conf

# -------------------------
# Key Bindings
# -------------------------
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard
map ctrl+shift+c send_text all \x03
map ctrl+shift+v send_text all \x16
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

# -------------------------
# Mouse Behavior
# -------------------------
mouse_hide_wait 3.0
mouse_map right press ungrabbed combine : copy_to_clipboard : clear_selection : paste_from_clipboard