misc {
    animate_manual_resizes = 1
    animate_mouse_windowdragging = 1
    enable_swallow = true
    swallow_regex = ^(kitty)$
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = true
}

xwayland {
    force_zero_scaling = true
}

ecosystem {
    no_update_news = true
    no_donation_nag = true
    enforce_permissions = true
}

