# Program Permissions
permission = /usr/(bin|local/bin)/grim, screencopy, allow
permission = /usr/(bin|local/bin)/wf-recorder, screencopy, allow
permission = /usr/(bin|local/bin)/hyprcap, screencopy, allow
permission = /usr/(bin|local/bin)/hyprpicker, screencopy, allow
permission = /usr/(bin|local/bin)/pipewire, screencopy, allow
permission = /usr/(bin|local/bin)/pipewire, screencopy, allow
permission = /usr/(bin|local/bin)/pipewire-pulse, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal, screencopy, allow

# Device Permissions
permission = gsr-ui-virtual-keyboard, keyboard, allow
permission = logitech-pro-gaming-keyboard, keyboard, allow
permission = .*, keyboard, deny