-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        inactive_timeout = 20.0,
        no_hardware_cursors = 1,
    },
    general = {
        snap = {
            enabled = true,
            window_gap = 20,
        },
    },
})

-- Bezier curves
hl.curve("almostLinearStep", { type = "bezier", points = { {0.385, 0.171}, {0.529, 1.152} } })

-- Animations
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 2.0,
    bezier = "almostLinearStep",
    style = "slide",
})
