general {
    ignore_dbus_inhibit = false
    ignore_wayland_inhibit = false
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' && ~/.dotfiles/scripts/desktop/toggle-shell.sh
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && ~/.dotfiles/scripts/desktop/toggle-shell.sh
}