
# ~/.config/hypr/hyprland.conf

##################
### ANIMATIONS ###
##################

source = ~/.config/hypr/animations/animation.conf

###############
### DISPLAY ###
###############

source = ~/.config/hypr/display/monitors.conf
source = ~/.config/hypr/display/rules.conf

################
### PROGRAMS ###
################

source = ~/.config/hypr/programs/autostart.conf
source = ~/.config/hypr/programs/programs.conf

#################
### VARIABLES ###
#################

source = ~/.config/hypr/variables/environment.conf
source = ~/.config/hypr/variables/permissions.conf
source = ~/.config/hypr/variables/misc.conf

#############
### THEME ###
#############

source = ~/.config/hypr/theme/border.conf
source = ~/.config/hypr/theme/theme.conf

#############
### INPUT ###
#############

source = ~/.config/hypr/input/input.conf
source = ~/.config/hypr/input/keybinds.conf

###############
### HYPRMOD ###
###############

source = ~/.config/hypr/hyprmod.conf