
# ~/.config/hypr/hyprland.conf

##################
### ANIMATIONS ###
##################

source = ~/.config/hypr/conf/animations/animation.conf

###############
### DISPLAY ###
###############

source = ~/.config/hypr/conf/display/monitors.conf
source = ~/.config/hypr/conf/display/rules.conf

################
### PROGRAMS ###
################

source = ~/.config/hypr/conf/programs/autostart.conf
source = ~/.config/hypr/conf/programs/programs.conf

#################
### VARIABLES ###
#################

source = ~/.config/hypr/conf/variables/environment.conf
source = ~/.config/hypr/conf/variables/permissions.conf
source = ~/.config/hypr/conf/variables/misc.conf

#############
### THEME ###
#############

source = ~/.config/hypr/conf/theme/border.conf
source = ~/.config/hypr/conf/theme/theme.conf

#############
### INPUT ###
#############

source = ~/.config/hypr/conf/input/input.conf
source = ~/.config/hypr/conf/input/keybinds.conf

###############
### PLUGINS ###
###############

source = ~/.config/hypr/conf/plugins/dynamic-cursors.conf

###############
### HYPRMOD ###
###############

source = ~/.config/hypr/conf/hyprmod.conf