general {
    ignore_dbus_inhibit = false
    ignore_wayland_inhibit = false
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off && ~/.dotfiles/scripts/desktop/toggle-shell.sh
    on-resume = hyprctl dispatch dpms on && ~/.dotfiles/scripts/desktop/toggle-shell.sh
}