# Set "Windows" key as main modifier
$MOD = SUPER

# App Control
bind = $MOD, S, exec, $music
bind = $MOD, J, exec, $media
bind = $MOD, D, exec, $discord
bind = $MOD, C, exec, $code
bind = $MOD, E, exec, $fileManager 
bind = $MOD, W, exec, $status 
bind = $MOD, B, exec, $browser
bind = $MOD, M, exec, $mail
bind = $MOD, O, exec, $notes
bind = $MOD SHIFT, B, exec, $privateBrowser
bind = $MOD, $MOD_L, exec, $menu
bind = $MOD, SPACE, exec, $noctalia controlCenter toggle
bind = $MOD, comma, exec, $noctalia settings toggle
bind = $MOD, period, exec, emote
bind = $MOD, RETURN, exec, $terminal
bind = $MOD SHIFT, RETURN, exec, $terminal-float

# Media Control
bindel = , XF86AudioRaiseVolume, exec, $noctalia volume increase
bindel = , XF86AudioLowerVolume, exec, $noctalia volume decrease
bindl = , XF86AudioMute, exec, $noctalia volume muteOutput
bindel = , XF86MonBrightnessUp, exec, $noctalia brightness increase
bindel = , XF86MonBrightnessDown, exec, $noctalia brightness decrease

# Screenshot Tools
bind = $MOD, PRINT, exec, $windowshot
bind = $MOD + SHIFT, S, exec, $regionshot
bind = , PRINT, exec, $screenshot

# Lockscreen Control
bind = $MOD + SHIFT, L, exec, hyprlock

# Monitor Control
bind = CTRL, F1, exec, ~/.dotfiles/scripts/desktop/toggle-brightness.sh 2 0 80
bind = CTRL, F2, exec, ~/.dotfiles/scripts/desktop/toggle-power.sh 2
bind = CTRL, F3, exec, ~/.dotfiles/scripts/desktop/toggle-brightness.sh 1 0 50 100
bind = CTRL, F4, exec, ~/.dotfiles/scripts/desktop/toggle-power.sh 1

# Focus Control
bind = $MOD, H, movefocus, l
bind = $MOD, J, movefocus, d
bind = $MOD, K, movefocus, u
bind = $MOD, L, movefocus, r

# Workspace Control
bind = $MOD, mouse_down, workspace, m-1
bind = $MOD, mouse_up, workspace, m+1
bind = $MOD, 1, workspace, 1
bind = $MOD, 2, workspace, 2
bind = $MOD, 3, workspace, 3
bind = $MOD, 4, workspace, 4
bind = $MOD, 5, workspace, 5
bind = $MOD, 6, workspace, 6
bind = $MOD, 7, workspace, 7
bind = $MOD, 8, workspace, 8
bind = $MOD, 9, workspace, 9
bind = $MOD, 0, workspace, 10

# Window Control
bind = , F11, fullscreen, 0
bind = $MOD, F, fullscreen, 1
bind = $MOD, Q, killactive
bind = $MOD SHIFT, Q, exec, $forceKillActive
bind = $MOD, V, togglefloating
bind = $MOD SHIFT, C, centerwindow
bindm = $MOD, mouse:272, movewindow
bindm = $MOD, mouse:273, resizewindow