[main]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\xff\xff\xfb\xc8\xff\xff\xfe>\xff\xff\xff\xe7\0\0\x5\x88\xff\xff\xfb\xc8\xff\xff\xfe>\xff\xff\xff\xe7\0\0\x5\x88\0\0\0\x1\x2\0\0\0\x4\x38\xff\xff\xfb\xc8\xff\xff\xfe>\xff\xff\xff\xe7\0\0\x5\x88)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x4 \0\0\a%\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[notification]
app=true
donation_message=false
show_msg=true
show_name=true
show_photo=true
sound=true

[onboarding]
completed=true
initial_setup_completed=true
last_environment=local
version=2

[permissions]
auto_grant\camera=true
auto_grant\camera_microphone=true
auto_grant\microphone=true
auto_grant\screen_contents=true
auto_grant\screen_contents_audio=true

[system]
confirm_on_close=false
download_path=/home/ELECTRO/Downloads
interface_language=system
notificationCounter=true
quit_in_close=true
spellCheckers=true
start_background=false
start_system=false
tray_icon=false
wayland=true

[website]
open_page=false
