[main]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4\xec\0\0\x5j\0\0\0\0\0\0\0\0\0\0\x4\xec\0\0\x5j\0\0\0\0\x2\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\x4\xec\0\0\x5j)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x4\xed\0\0\x5S\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[notification]
app=true
donation_message=false
show_msg=true
show_name=true
show_photo=true

[onboarding]
completed=true
last_environment=local
version=2

[system]
quit_in_close=true
spellCheckers=true
start_background=false
start_system=false
wayland=true

[website]
open_page=false
