proton_version = "Proton-Tkg Latest"
prefix_path = "~/.proton"
shared_prefix = true
auto_shortcuts = true
use_umu = true
mangohud = false
gamescope = false
gamemode = true

[env]
  PROTON_USE_NTSYNC = "1"
  PROTON_USE_WOW64 = "1"

[gamescope_opts]
  width = 2560
  height = 1440
  fullscreen = true
