proton_version = "Proton - Experimental"
prefix_path = "~/.proton"
use_umu = true
mangohud = false
gamescope = false
gamemode = true

[env]
  PROTON_DISCORD_BRIDGE = "0"
  PROTON_ENABLE_WAYLAND = "1"
  PROTON_USE_NTSYNC = "1"
  PROTON_USE_WOW64 = "1"

[gamescope_opts]
  width = 2560
  height = 1440
  fullscreen = true
