hl.on("hyprland.start", function ()
  hl.exec_cmd("dbus-update-activation-environment --all")
  hl.exec_cmd("/usr/lib/hyprpolkitagent")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("hyprctl setcursor lightning-jewel 24")
  hl.exec_cmd("qs -c noctalia-shell")
  hl.exec_cmd("gsr-ui launch-daemon")
  hl.exec_cmd("linux-wallpaperengine --silent --screen-root DP-1 --bg 2638946149")
  hl.exec_cmd("linux-wallpaperengine --silent --disable-mouse --disable-parallax --set-property timeofday=3 --screen-root HDMI-A-1 --bg 2504353624")
  hl.exec_cmd("~/.dotfiles/scripts/discord.sh")
  hl.exec_cmd("feishin")
  hl.exec_cmd("steam -silent")
end)