exec-once = dbus-update-activation-environment --all
exec-once = /usr/lib/hyprpolkitagent
exec-once = hypridle
exec-once = hyprctl setcursor lightning-jewel 15
exec-once = qs -c noctalia-shell
exec-once = gsr-ui launch-daemon
exec-once = linux-wallpaperengine --silent --screen-root DP-1 --bg 2638946149
exec-once = linux-wallpaperengine --silent --disable-mouse --disable-parallax --set-property timeofday=3 --screen-root HDMI-A-1 --bg 2504353624
exec-once = ~/.dotfiles/scripts/discord.sh
exec-once = feishin
exec-once = steam -silent