# Set Noctalia shell call
$noctalia = qs -c noctalia-shell ipc call

# Set programs
$music = feishin
$media = jellyfin-desktop
$terminal = kitty
$terminal-float = kitty --class kitty-floating
$browser = librewolf
$privateBrowser = librewolf --private-window
$discord = discord-canary
$code = vscodium-insiders
$windowshot = hyprcap shot window --no-notify --copy
$regionshot = hyprcap shot region --freeze --no-notify --copy
$screenshot = hyprcap shot monitor:active --no-notify --copy
$fileManager = thunar
$mail = thunderbird
$notes = obsidian

# Set commands
$menu = $noctalia launcher toggle
$status = ~/.dotfiles/scripts/desktop/refresh.sh
$forceKillActive = kill -9 $(hyprctl activewindow -j | jq '.pid')