# Set Noctalia shell call
$noctalia = qs -c noctalia-shell ipc call

# Set programs
$music = feishin
$media = jellyfin-desktop
$terminal = kitty
$terminal-float = kitty --class kitty-floating
$browser = librewolf
$privateBrowser = librewolf --private-window
$discord = ~/.dotfiles/scripts/discord.sh
$code = vscodium-insiders
$hyprcap = ~/.dotfiles/scripts/hyprcap.sh
$screenshot = hyprcap shot monitor:active --copy
$fileManager = thunar
$mail = thunderbird
$notes = obsidian

# Set commands
$menu = $noctalia launcher toggle
$status = ~/.dotfiles/scripts/desktop/refresh.sh
$forceKillActive = kill -9 $(hyprctl activewindow -j | jq '.pid')