[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates

[templates.wofi]
input_path = "~/.config/noctalia/templates/wofi.css"
output_path = "~/.config/wofi/style.css"

[templates.pandora]
input_path = "~/.config/noctalia/templates/pandora.json"
output_path = "~/.local/share/PandoraLauncher/themes/noctalia.json"